version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    restart: always
  s3:
    image: minio/minio
    ports:
      - 9000:9000
    command: [server, /data]
    environment:
      - MINIO_ACCESS_KEY=hogehoge
      - MINIO_SECRET_KEY=hogehoge
      - MINIO_REGION=ap-northeast-1
# networks:
#   default:
#     external:
#       name: hollein-network
