AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hollein SAM is for portzamparc

Globals:
  Function:
    Timeout: 5

Resources:
  GitHubContributionCrawler: # LambdaFunctionName
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      FunctionName: github-contribution-crawler
      Policies: AmazonDynamoDBFullAccess
      Runtime: go1.x
      Tracing: Active
      Environment: # env variables on Lambda
        Variables:
          GITHUB_ACCESS_TOKEN: ''

      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            # Every 12:00 pm
            Schedule: cron(0 12 * * ? *) # https://amzn.to/3kUY2jj

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
