AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hollein SAM is for portzamparc
Globals:
  Function:
    Timeout: 5
Resources:
  GitHubContributionCrawler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      FunctionName: github-contribution-crawler
      Policies: AmazonDynamoDBFullAccess
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: ''
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            # 毎日11時59分 (59 11 * * ? *)
            # 5分ごと (0/5 * * * ? *)　
            Schedule: cron(0/5 * * * ? *)
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataTable
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
